version: '3.9'
services:
  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=guma
    ports:
      - "5431:5432"
    healthcheck:
      test: [ "CMD-SHELL", "psql -h localhost -U postgres -d guma -c 'SELECT 1;'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ./.docker/db/data:/var/lib/postgresql/:delegated

  api:
    image: matheusvict/gumaapi:latest
    hostname: api
    environment:
      - SPRING.PROFILES.ACTIVE=prod
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=guma
      - PGUSER=postgres
      - PGPASSWORD=123
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  client:
    image: matheusvict/gumaclient:latest
    hostname: client
    environment:
      - BASE_URL_SERVER=api
    ports:
      - "3000:80"
    depends_on:
      - api


networks:
  default:
    driver: bridge
    name: guma-network