spring:
  application:
    name: Guma-api
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    ollama:
      chat:
        model: deepseek-r1:1.5b
        options:
          temperature: 0.1

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
