spring:
  application:
    name: Guma-api
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    ollama:
      chat:
        model:  tinyllama #deepseek-r1:1.5b
        #options:
         # temperature: 0.4
          #max-tokens: 512
          #top-k: 20
          #top-p: 0.7
          #frequency-penalty: 1.2
          #presence-penalty: 1.1
          #stop-sequences: [ "###", "END OF RESPONSE" ]
          #keep-alive: 10m

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
